### ISSUE TITLE
Gold problem

### ISSUE THREAD

**Issue by icekylinH** [william-Dic/DeepBattler#3]
why the script ask me to buy minion even I only have one gold.

**Comment by icekylinH** [comment]
When I compiled the file, the only issue I encountered was that when I tried to add a reference, it told me that HearthstoneDeckTracker.exe is not a valid COM file.

**Comment by william-Dic** [comment]
Thank you for pointing those out really appreciate it. Regarding the situation where DeepBattler asks you to buy a minion when you don't have enough money, I believe this is due to a response time issue. When the response time is too long and the player takes action while DeepBattler is still responding, the response might reflect a previous game state instead of the current one. I'm considering using a more efficient model construction to reduce its response time. I hope this helps and that you've also resolved the compile problem.
